const QUESTIONS = [
  "Explain the concept of containerization in one paragraph.",
  "What is the difference between a process and a thread?",
  "Write a Python function to find the nth Fibonacci number.",
  "Explain how DNS resolution works step by step.",
  "What are the SOLID principles in software engineering?",
  "Describe the CAP theorem and its implications for distributed systems.",
  "Write a SQL query to find the second highest salary in a table.",
  "What is the difference between TCP and UDP?",
  "Explain how a hash table works internally.",
  "What are the main differences between REST and GraphQL?",
  "Write a function to check if a string is a valid palindrome.",
  "Explain the concept of eventual consistency.",
  "What is a mutex and when would you use one?",
  "Describe the observer design pattern with an example.",
  "What are Kubernetes pods and how do they differ from containers?",
  "Explain the difference between optimistic and pessimistic locking.",
  "Write a function to merge two sorted arrays.",
  "What is a load balancer and what algorithms can it use?",
  "Explain how TLS/SSL handshake works.",
  "What are the advantages of microservices over monolithic architecture?",
  "Write a function to detect a cycle in a linked list.",
  "Explain the concept of database sharding.",
  "What is the difference between symmetric and asymmetric encryption?",
  "Describe the strategy design pattern.",
  "What is a message queue and when should you use one?",
  "Explain the difference between horizontal and vertical scaling.",
  "Write a function to implement binary search.",
  "What are WebSockets and how do they differ from HTTP?",
  "Explain the concept of idempotency in API design.",
  "What is a reverse proxy and how does it work?",
  "Write a function to flatten a nested array.",
  "Explain the concept of circuit breaker pattern.",
  "What are the different types of database indexes?",
  "Describe the factory method design pattern.",
  "What is rate limiting and how can it be implemented?",
  "Explain the difference between authentication and authorization.",
  "Write a function to find all permutations of a string.",
  "What is a CDN and how does it improve performance?",
  "Explain the concept of blue-green deployment.",
  "What are environment variables and why are they important?",
  "Write a regular expression to validate an email address.",
  "Explain how garbage collection works in managed languages.",
  "What is the difference between SQL and NoSQL databases?",
  "Describe the adapter design pattern.",
  "What is observability and how does it differ from monitoring?",
  "Explain the concept of immutable infrastructure.",
  "Write a function to implement a basic LRU cache.",
  "What is service mesh and what problems does it solve?",
  "Explain the concept of canary deployment.",
  "What are the benefits of infrastructure as code?",
];

export function getRandomQuestion(): string {
  return QUESTIONS[Math.floor(Math.random() * QUESTIONS.length)]!;
}

export function getQuestionPool(): string[] {
  return [...QUESTIONS];
}
