apiVersion: v1
kind: Secret
metadata:
  name: openid-client-secret
  namespace: openshift-config
  labels:
    {{- include "maas-pulse.labels" . | nindent 4 }}
type: Opaque
data:
  clientSecret: {{ .Values.realm.openshiftClientSecret | b64enc }}
